// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.DAL;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230920003437_SomeUpdate")]
    partial class SomeUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomCardUserAccount", b =>
                {
                    b.Property<Guid>("LikedCustomCardsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LikedUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikedCustomCardsId", "LikedUsersId");

                    b.HasIndex("LikedUsersId");

                    b.ToTable("CustomCardUserAccount");
                });

            modelBuilder.Entity("DeckUserAccount", b =>
                {
                    b.Property<Guid>("LikedDecksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LikedUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikedDecksId", "LikedUsersId");

                    b.HasIndex("LikedUsersId");

                    b.ToTable("DeckUserAccount");
                });

            modelBuilder.Entity("Repositories.Models.CustomCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("CustomCards");

                    b.HasDiscriminator<string>("Discriminator").HasValue("CustomCard");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repositories.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeckCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("Decks");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Deck");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Repositories.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Repositories.Models.CustomCardOTD", b =>
                {
                    b.HasBaseType("Repositories.Models.CustomCard");

                    b.Property<Guid?>("CardSetterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SettingDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("CardSetterId");

                    b.HasDiscriminator().HasValue("CustomCardOTD");
                });

            modelBuilder.Entity("Repositories.Models.DeckOTD", b =>
                {
                    b.HasBaseType("Repositories.Models.Deck");

                    b.Property<Guid?>("DeckSetterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SettingDate")
                        .HasColumnType("datetime2");

                    b.HasIndex("DeckSetterId");

                    b.HasDiscriminator().HasValue("DeckOTD");
                });

            modelBuilder.Entity("CustomCardUserAccount", b =>
                {
                    b.HasOne("Repositories.Models.CustomCard", null)
                        .WithMany()
                        .HasForeignKey("LikedCustomCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("LikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeckUserAccount", b =>
                {
                    b.HasOne("Repositories.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("LikedDecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("LikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Models.CustomCard", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "OwnerAccount")
                        .WithMany("OwnedCustomCards")
                        .HasForeignKey("OwnerAccountId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("Repositories.Models.Deck", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "OwnerAccount")
                        .WithMany("OwnedDecks")
                        .HasForeignKey("OwnerAccountId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("Repositories.Models.CustomCardOTD", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "CardSetter")
                        .WithMany()
                        .HasForeignKey("CardSetterId");

                    b.Navigation("CardSetter");
                });

            modelBuilder.Entity("Repositories.Models.DeckOTD", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "DeckSetter")
                        .WithMany()
                        .HasForeignKey("DeckSetterId");

                    b.Navigation("DeckSetter");
                });

            modelBuilder.Entity("Repositories.Models.UserAccount", b =>
                {
                    b.Navigation("OwnedCustomCards");

                    b.Navigation("OwnedDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
