// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.DAL;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240415120809_UpdatedCards")]
    partial class UpdatedCards
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomCardUserAccount", b =>
                {
                    b.Property<Guid>("LikedCustomCardsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LikedUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikedCustomCardsId", "LikedUsersId");

                    b.HasIndex("LikedUsersId");

                    b.ToTable("CustomCardUserAccount");
                });

            modelBuilder.Entity("DeckUserAccount", b =>
                {
                    b.Property<Guid>("LikedDecksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LikedUsersId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LikedDecksId", "LikedUsersId");

                    b.HasIndex("LikedUsersId");

                    b.ToTable("DeckUserAccount");
                });

            modelBuilder.Entity("Repositories.Models.CustomCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovalState")
                        .HasColumnType("int");

                    b.Property<string>("CardDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CardName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Regions")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("CustomCards");
                });

            modelBuilder.Entity("Repositories.Models.CustomCardOTD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CardSetterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SettingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardId");

                    b.HasIndex("CardSetterId");

                    b.ToTable("CustomCardsOTD");
                });

            modelBuilder.Entity("Repositories.Models.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeckCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeckName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NumberOfLikes")
                        .HasColumnType("int");

                    b.Property<Guid?>("OwnerAccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OwnerAccountId");

                    b.ToTable("Decks");
                });

            modelBuilder.Entity("Repositories.Models.DeckOTD", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DeckSetterId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SettingDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeckId");

                    b.HasIndex("DeckSetterId");

                    b.ToTable("DecksOTD");
                });

            modelBuilder.Entity("Repositories.Models.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Permissions")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("CustomCardUserAccount", b =>
                {
                    b.HasOne("Repositories.Models.CustomCard", null)
                        .WithMany()
                        .HasForeignKey("LikedCustomCardsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("LikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeckUserAccount", b =>
                {
                    b.HasOne("Repositories.Models.Deck", null)
                        .WithMany()
                        .HasForeignKey("LikedDecksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", null)
                        .WithMany()
                        .HasForeignKey("LikedUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Repositories.Models.CustomCard", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "OwnerAccount")
                        .WithMany("OwnedCustomCards")
                        .HasForeignKey("OwnerAccountId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("Repositories.Models.CustomCardOTD", b =>
                {
                    b.HasOne("Repositories.Models.CustomCard", "Card")
                        .WithMany()
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", "CardSetter")
                        .WithMany()
                        .HasForeignKey("CardSetterId");

                    b.Navigation("Card");

                    b.Navigation("CardSetter");
                });

            modelBuilder.Entity("Repositories.Models.Deck", b =>
                {
                    b.HasOne("Repositories.Models.UserAccount", "OwnerAccount")
                        .WithMany("OwnedDecks")
                        .HasForeignKey("OwnerAccountId");

                    b.Navigation("OwnerAccount");
                });

            modelBuilder.Entity("Repositories.Models.DeckOTD", b =>
                {
                    b.HasOne("Repositories.Models.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repositories.Models.UserAccount", "DeckSetter")
                        .WithMany()
                        .HasForeignKey("DeckSetterId");

                    b.Navigation("Deck");

                    b.Navigation("DeckSetter");
                });

            modelBuilder.Entity("Repositories.Models.UserAccount", b =>
                {
                    b.Navigation("OwnedCustomCards");

                    b.Navigation("OwnedDecks");
                });
#pragma warning restore 612, 618
        }
    }
}
